name: amd64

on:
  schedule:
    - cron: '0 8 5,15,25 * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'x86_64平台'
        type: boolean
        required: true
        default: true

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login Gitlab Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Clone Overleaf Gitlab Repo
        run: |
          git clone https://gitlab.com/overleaf-open/overleaf.git
      
      - name: Replace Dockerfile
        run: |
          cp ./Dockerfile.base.arm64 ./overleaf/server-ce/Dockerfile-base

      - name: Build Push Docker images[Base]
        uses: docker/build-push-action@v4
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          push: true
          tags: registry.gitlab.com/overleaf-open/overleaf/sharelatex-base:amd64-latest

      - name: Build Push Docker images[Web]
        uses: docker/build-push-action@v4
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile
          push: true
          tags: registry.gitlab.com/overleaf-open/overleaf/sharelatex:amd64-origin
          build-args: |
            SHARELATEX_BASE_TAG=registry.gitlab.com/overleaf-open/overleaf/sharelatex-base:amd64-latest

      
      - name: Build Push Docker images[Tex Latest]
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.amd64
          push: true
          tags: registry.gitlab.com/overleaf-open/overleaf/sharelatex:amd64-latest

