name: arm64

on:
#   schedule:
#     - cron: '0 8 5,15,25 * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'arm64平台'
        type: boolean
        required: true
        default: true

jobs:
  build-all:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm	
    steps:
      - uses: actions/checkout@v3

      - name: Login Gitlab Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
    
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2


      - name: Clone Overleaf Gitlab Repo
        run: |
          git clone https://gitlab.com/overleaf-open/overleaf.git
          
      - name: Build Push Docker images[Base]
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          push: true
          tags: registry.gitlab.com/overleaf-open/overleaf/sharelatex-base:arm64-latest

      - name: Build Push Docker images[Web]
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile
          push: true
          tags: registry.gitlab.com/overleaf-open/overleaf/sharelatex:arm64-origin
          build-args: |
            SHARELATEX_BASE_TAG=registry.gitlab.com/overleaf-open/overleaf/sharelatex-base:arm64-latest

      - name: Build Push Docker images[Tex Latest]
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          context: .
          file: ./Dockerfile.arm64
          push: true
          tags: registry.gitlab.com/overleaf-open/overleaf/sharelatex:arm-latest
