name: build

on:
  schedule:
    - cron: '0 8 5,15,25 * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '手动构建'
        type: boolean
        required: true
        default: true

jobs:
  # This workflow contains a single job called "build"
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login Registry
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN

      - name: Run Build
        run: |
          cp ./amd64/* ./
          current_dir=$(pwd)
          git clone https://gitlab.com/overleaf-open/overleaf.git
          cp ./Makefile ./overleaf/server-ce/Makefile
          cd overleaf/server-ce
          # make
          cd "$current_dir"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -l
          # docker build -t registry.gitlab.com/overleaf-open/overleaf/sharelatex:amd64-full .
          # docker push registry.gitlab.com/overleaf-open/overleaf/sharelatex:amd64-full

