name: multi

on:
  schedule:
    - cron: '0 8 5,15,25 * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '多平台'
        type: boolean
        required: true
        default: true

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login Gitlab Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Clone Overleaf Gitlab Repo
        run: |
          git clone https://gitlab.com/overleaf-open/overleaf.git
        
      - name: Build Push Docker images[Base]
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          push: true
          tags: openoverleaf/sharelatex-base:latest

      - name: Build Push Docker images[Web]
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile
          push: true
          tags: openoverleaf/sharelatex:origin
          build-args: |
            SHARELATEX_BASE_TAG=openoverleaf/sharelatex-base:latest

      
      - name: Build Push Docker images[Tex Latest]
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          tags: openoverleaf/sharelatex:latest
      
